### ISSUE TITLE
quote and proc-macro2 running when being supposed to be interpreted by the compiler

### ISSUE THREAD

**Issue by SatoCodingStuff** [popcorn-kernel/popcorn#5]
see https://github.com/popcorn-kernel/popcorn/actions/runs/5556890269

**Comment by SatoTsukasaCode** [comment]
looks like the compiler is recommending to: "" note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.""

**Comment by SatoCodingStuff** [comment]
should be fix in #13
