### ISSUE TITLE
Can you please remove the unneeded set_color! and set the color to color yellow?

### ISSUE THREAD

**Issue by janTatesa** [popcorn-kernel/popcorn#56]
There was a pr that somebody "fixed" the colors by setting the "Welcome to the" to white (even tthough it was yellow) and put the set_color! which is implied. I fixed the "fix' in the backspace pr, buut for some reason its still there. i am new to git but please fix it

**Comment by SatoCodingStuff** [comment]
The title was supposed to be in white and not yellow, and the set color eas for the text that will be typed by the user next.

**Comment by janTatesa** [comment]
But the printwith colors macro implies set color

**Comment by janTatesa** [comment]
```#[macro_export]
macro_rules! print_with_colors {
    ( $( $x:expr ),* ) => {
        {
            $(
                $x.print_to_vga();
            )*
        }
        set_color!(Color::White, Color::Black);
    };
}```

**Comment by SatoCodingStuff** [comment]
The last print_with_ color is in blue, we want the next lines ti be white

**Comment by janTatesa** [comment]
But as you can see the macro calls set color White Black

**Comment by janTatesa** [comment]
At the end

**Comment by janTatesa** [comment]
The text is white

**Comment by janTatesa** [comment]
![image](https://github.com/popcorn-kernel/popcorn/assets/100917739/2ff31107-c618-47ec-8f72-1892012fd439)

**Comment by SatoCodingStuff** [comment]
Ah I see. I'll merge it then
