### ISSUE TITLE
seed executable format (Simple Effective Executable Design)

### ISSUE THREAD

**Issue by electron271** [popcorn-kernel/popcorn#66]

**Comment by janTatesa** [comment]
Wait isnt ELF the standard?

**Comment by janTatesa** [comment]
I mean wouldnt we have to write our own assembler?

**Comment by SatoCodingStuff** [comment]
I have suggested ELF but they decided to make a new one

**Comment by janTatesa** [comment]
Dont we want it to be posix?

**Comment by sparkles-laurel** [comment]
With a kernel module it'll be posix

**Comment by janTatesa** [comment]
Isnt elf posix?

**Comment by sparkles-laurel** [comment]
It isn't from what I see

**Comment by sparkles-laurel** [comment]
It isn't from what I see
It's just adopted by POSIX

**Comment by sparkles-laurel** [comment]
Firs existed in SysV

**Comment by janTatesa** [comment]
We should use elf. We shouldnt make everything by ourselfes. Theres a reason for people to use a desktop environment instead of window manager - setting up everything yourself makes a lack of integration

**Comment by SatoCodingStuff** [comment]
I agree with tabo here.

**Comment by janTatesa** [comment]
I visualise far far future popcorn as freebsd in rust

**Comment by SatoCodingStuff** [comment]
Please, let's not make everything from scratch. We have great software that we can use. Let's not make our own filesystem, not another executable format, not another browser etc.

**Comment by janTatesa** [comment]
There's a balance between using random stuff that does not work together (like my arch system), and making everything so tightly that if you modify it it breaks like windows

**Comment by janTatesa** [comment]
Windows makes everything themselves

**Comment by janTatesa** [comment]
Thats why theyre so crappy

**Comment by sparkles-laurel** [comment]
> I visualise far far future popcorn as freebsd in rust

And this is what we do not want

**Comment by sparkles-laurel** [comment]
> Thats why theyre so crappy

No it's because they have to maintain their legacy garbage after shoving their inferior and faulty operating system down every single computer user's throat

**Comment by sparkles-laurel** [comment]
also they don't abide by standards

**Comment by sparkles-laurel** [comment]
If we abide by standards, and make a POSIX-compatible executable format it's fine

**Comment by sparkles-laurel** [comment]
If we are gonna use ELF, we should put on top of it.

**Comment by sparkles-laurel** [comment]
This is not a rewrite of Linux or FreeBSD in Rust.

**Comment by janTatesa** [comment]
Okay so good luck making your own assembler

**Comment by sparkles-laurel** [comment]
> If we are gonna use ELF, we should put on top of it.

We adopt ELF, but we extend it in a reasonable way.

**Comment by janTatesa** [comment]
How?

**Comment by sparkles-laurel** [comment]
i need to think about it

**Comment by sparkles-laurel** [comment]
> Please, let's not make everything from scratch. We have great software that we can use. Let's not make our own filesystem, not another executable format, not another browser etc.

@SatoTsukasaCode, I already finished draft spec for a filesystem.

**Comment by janTatesa** [comment]
Like an executable is a message to the kernel "Load this process". How cant we extend it?

**Comment by janTatesa** [comment]
Why do we need a separate filesystem too?

**Comment by sparkles-laurel** [comment]
well, we wanna have some dignity while also maintaining compatibility

**Comment by sparkles-laurel** [comment]
And not be another "clone of X in Rust"

**Comment by janTatesa** [comment]
I mean people often share /home partition when dualbooting linux and linux or linux and bsd or basd and bsd, so we will rather support existing filesystytems

**Comment by janTatesa** [comment]
Creating a new filesystem makes fragmentation

**Comment by janTatesa** [comment]
Same applies to a new executable format

**Comment by sparkles-laurel** [comment]
> I mean people often share /home partition when dualbooting linux and linux or linux and bsd or basd and bsd, so we will rather support existing filesystytems

I thought I said we will support other filesystems while making our own one too

**Comment by janTatesa** [comment]
But why? Whats the mistake of ext4?

**Comment by sparkles-laurel** [comment]
If it didn't have issues btrfs wouldn't exist

**Comment by sparkles-laurel** [comment]
What about making ext5?

**Comment by janTatesa** [comment]
> If it didn't have issues btrfs wouldn't exist

Okay whats the mistake of btrfs? I mean yes we wanna make a rust ecosystem but theres this already https://gitlab.redox-os.org/redox-os/tfs

**Comment by sparkles-laurel** [comment]
Rust is considered as a language where people rewrite pre-existing stuff. If we don't have some dignity, we will probably just rewrite FreeBSD or Linux in Rust, and this is not what we are.

**Comment by sparkles-laurel** [comment]
We are not trying to rewrite pre-existing stuff

**Comment by sparkles-laurel** [comment]
inodefs was my first step in this

**Comment by janTatesa** [comment]
> What about making ext5?

![image](https://github.com/popcorn-kernel/popcorn/assets/100917739/f8bc4fb8-edf2-43ae-811b-51c40e2d08a5)
Idk ext4 is good enough.

**Comment by janTatesa** [comment]
> Rust is considered as a language where people rewrite pre-existing stuff. If we don't have some dignity, we will probably just rewrite FreeBSD or Linux in Rust, and this is not what we are.

I didnt mean we will rewrite stuff. But we will make a rust alternatives to these

**Comment by janTatesa** [comment]
> I visualise far far future popcorn as freebsd in rust

I meant a freebsd alternative written in rust

**Comment by sparkles-laurel** [comment]
> we will make rust alternatives to these

And you say we are gonna clone the same architecture and not add anything on top. This is called rewriting

**Comment by janTatesa** [comment]
> > we will make rust alternatives to these
> > And you say we are gonna clone the same architecture and not add anything on top. This is called rewriting

No, by alternative i meant that users with similar values as freebsd users will consider it as an alternative that is written in rust

**Comment by sparkles-laurel** [comment]
This means it'll be unused

**Comment by janTatesa** [comment]
Why?

**Comment by janTatesa** [comment]
I simply said that i want to make an open source unix OS that is well integrated together written in rust, that doesnt cause much fragmdentation

**Comment by SatoCodingStuff** [comment]
>>
> @SatoTsukasaCode, I already finished draft spec for a filesystem.

Didn't we settle not to make a filesystem? Please, let's not.

**Comment by janTatesa** [comment]
> > > 
> > 
> > 
> > @SatoTsukasaCode, I already finished draft spec for a filesystem.
> 
> Didn't we settle not to make a filesystem? Please, let's not.
You made a poll. Lets see about opinions of other people. Its me and you against sparky rn

**Comment by SatoCodingStuff** [comment]
Even before the poll. It was a lot before the rewrite

**Comment by sparkles-laurel** [comment]
I maintain drafts for some system utilities outside popcorn, you mean I don't have right to do that and also port them to popcorn?

**Comment by sparkles-laurel** [comment]
This was supposed to be a learning project as well.

**Comment by sparkles-laurel** [comment]
Honestly, there's only one thing I demand from popcorn myself:
**primary initialisation of userspace should take no longer than half a second**

**Comment by sparkles-laurel** [comment]
I have a draft for that too

**Comment by SatoCodingStuff** [comment]
> I maintain drafts for some system utilities outside popcorn, you mean I don't have right to do that and also port them to popcorn?

Yes.

**Comment by sparkles-laurel** [comment]
Also, what is your problem with me proposing a new filesystem, writing its initial implementation for Linux, then porting it to popcorn?

**Comment by sparkles-laurel** [comment]
> > I maintain drafts for some system utilities outside popcorn, you mean I don't have right to do that and also port them to popcorn?
> 
> Yes.
So you mean I don't have the right to design stuff outside popcorn, then integrate them into popcorn?

**Comment by sparkles-laurel** [comment]
During the first term of our inactivity, I had time to draft a lot of specifications. You mean I worked for nothing?

This is sad to see tbh

**Comment by SatoCodingStuff** [comment]
> > > I maintain drafts for some system utilities outside popcorn, you mean I don't have right to do that and also port them to popcorn?
> > 
> > Yes.
> So you mean I don't have the right to design stuff outside popcorn, then integrate them into popcorn?

Oh wait, i miss read. I don't mean that you don't have the right to, I meant that it's not the top of our priorities now let's make a working kernel and then work on little additions.

**Comment by electron271** [comment]
look, lets just stick with ELF and a existing fs (e.g ext), its not worth it to make our own
the poll in the discord has already decided

**Comment by electron271** [comment]
closing as not planned due to elf being used
