### ISSUE TITLE
[BUG] configure.sh does not include `rust-src` in components.

### ISSUE THREAD

**Issue by sparkles-laurel** [popcorn-kernel/popcorn#72]
## Summary
`configure.sh` is supposed to configure the toolchain for popcorn compilation
the toolchain for compiling a bare metal executable requires the `rust-src` component

```bash
# install nightly toolchain
rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
 ```

this line is absent in `configure.sh`

## Steps to reproduce
0. Make sure your environment lacks the `rust-src` component
1. Clone popcorn repository
2. Change into the popcorn repository
3. Run `./configure.sh`
4. Run `cargo build`
5. Observe

## Expected behaviour
During execution of `configure.sh`, the component `rust-src` was supposed to be installed and `cargo build` should run flawlessly.

## Actual behaviour
`cargo build` complains about absence of `rust-src`

**Comment by SatoCodingStuff** [comment]
I'm home in 30 minutes ill fix it

**Comment by sparkles-laurel** [comment]
can i merge the pr
